// Define the type for the 'values' array items
interface ReviewItem {
	name: string;
	text: string;
	score: number;
	number: number;
	short_text: string;
}

const reviews: ReviewItem[] = [
	{
		name: 'ServiceGen1',
		text: 'Great service! The synthetic data generated for my database was exactly what I needed. Highly recommended!',
		score: 5,
		number: 1,
		short_text:
			'Great service! The synthetic data generated for my database was exactly what I needed.'
	},
	{
		name: 'ServiceGen2',
		text: 'I am impressed with the quality of the synthetic data generated by this service. It saved me a lot of time and effort.',
		score: 4,
		number: 2,
		short_text: 'I am impressed with the quality of the synthetic data generated by this service.'
	},
	{
		name: 'ServiceGen3',
		text: 'The synthetic data provided by this service helped me in testing and development. Good job!',
		score: 4,
		number: 3,
		short_text: 'The synthetic data provided by this service helped me in testing and development.'
	},
	{
		name: 'ServiceGen4',
		text: 'I had a great experience with this service. The generated data was realistic and diverse.',
		score: 5,
		number: 4,
		short_text:
			'I had a great experience with this service. The generated data was realistic and diverse.'
	},
	{
		name: 'ServiceGen5',
		text: 'The synthetic data was delivered promptly, and it perfectly matched my requirements. Will use again!',
		score: 5,
		number: 5,
		short_text:
			'The synthetic data was delivered promptly, and it perfectly matched my requirements.'
	},
	{
		name: 'ServiceGen6',
		text: 'The generated data was of high quality and helped me in testing various scenarios. Thank you!',
		score: 4,
		number: 6,
		short_text: 'The generated data was of high quality and helped me in testing various scenarios.'
	},
	{
		name: 'ServiceGen7',
		text: 'I am satisfied with the synthetic data generated by this service. It was easy to integrate into my project.',
		score: 4,
		number: 7,
		short_text:
			'I am satisfied with the synthetic data generated by this service. It was easy to integrate into my project.'
	},
	{
		name: 'ServiceGen8',
		text: 'The generated data was consistent and reliable. It exceeded my expectations. Thanks!',
		score: 5,
		number: 8,
		short_text: 'The generated data was consistent and reliable. It exceeded my expectations.'
	},
	{
		name: 'ServiceGen9',
		text: 'This service provided me with the synthetic data I needed for my analysis. Great service!',
		score: 5,
		number: 9,
		short_text:
			'This service provided me with the synthetic data I needed for my analysis. Great service!'
	},
	{
		name: 'ServiceGen10',
		text: 'I highly recommend this service for generating synthetic data. Its a valuable tool for data testing and development.',
		score: 5,
		number: 10,
		short_text:
			'I highly recommend this service for generating synthetic data. Its a valuable tool for data testing and development.'
	}
];

// Export the 'load' function
export function load() {
	return {
		items: reviews
	};
}
