name: npm lint and check

on:
  push:
    branches:
      - main

jobs:
  lint_and_check:
    name: Lint and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --force

      - name: Run linting
        run: npm run lint

      - name: Run npm check
        run: npm check
